### ISSUE TITLE
🪲 bug(builder): File extraction fails 

### ISSUE THREAD

**Issue by ErikssonJoakim** [Byloth/cmangos-docker#15]
Hello! I recently found your project while having the same idea to dockerize cmangos. Seeing the great work you've already done I see no reason not to use your images to further my project.

## Description
I'm following the wiki starter guide and I noticed the extract argument and consequent function does not extract any files. I'm using the `classic` image but I assume this is a problem for all expansions

## How to reproduce

```
docker pull ghcr.io/byloth/cmangos/classic:latest &&
docker pull ghcr.io/byloth/cmangos/classic/builder:latest
```

```
docker run --rm \
           --volume "cmangos_mangosd_data:/home/mangos/data" \
           --volume "<PATH>:/home/mangos/wow-client" \
    \
    ghcr.io/byloth/cmangos/classic/builder:latest extract
```

## Excepted behaviour

Temporary container extracts all files necessary for mangosd

## Screenshots

Start extracting MaNGOS data: DBCs/maps `0`, vmaps `0`, mmaps `0` using  CPU threads
![Screenshot 2024-02-26 at 20 24 25](https://github.com/Byloth/cmangos-docker/assets/75730728/733184a4-01be-4238-a40b-52e1ffe2a88c)

**Comment by Byloth** [comment]
Hi! 🙃
Thank you for your contribution!

Your issue highlighted a problem with the Wiki I wrote... Damn! 😅

It seems that a couple of Docker arguments are missing, which are necessary for the extraction to run correctly: `-it`.
I will solve this problem directly on the Wiki; I will also look for other similar errors.

Here is the correct command for extraction:

```sh
docker run -it --rm \
           --volume "cmangos_mangosd_data:/home/mangos/data" \
           --volume "<PATH>:/home/mangos/wow-client" \
    \
    ghcr.io/byloth/cmangos/classic/builder:latest extract
```

---

Thank you again for your interest in this project! 🥹
