### ISSUE TITLE
bug: Error while applying `5325_spell_list.sql` update

### ISSUE THREAD

**Issue by Byloth** [Byloth/cmangos-docker#21]
The user **@nosralan1** wrote me this e-mail:

> Hi Byloth,
>
> I tried your instructions for “getting started” to setup the cmangos in docker. So far it worked until the step: Database initialization
> While the database update is partly successful, I received the error:
>
> ```
>  - Applying Updates/5323_Hrothgars_Landing.sql ... SUCCESS
>  - Applying Updates/5324_Loot_DBErrors.sql ... SUCCESS
>  - Applying Updates/5325_spell_list.sql ... FAILED!
>
> ERROR 1175 (HY000) at line 28: You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column
> ```
>
> I tried to fix while setting the `sql_safe_update=0` as part of the docker-compose but without any success.
> Do you have a hint how I can solve this issue?

**Comment by Byloth** [comment]
Hi @nosralan1!
I'm glad you started using my "CMaNGOS Docker" project.🙃

I'm sorry you're having this problem; I've never had this problem, honestly.
I don't know if the problem is due to my project or if it's the original [CMaNGOS](https://github.com/cmangos) project that my project just wrapped around.

**BUT...** Don't worry!  
I'm gonna ask to the CMaNGOS developers on their [Discord server](https://discord.gg/Dgzerzb)...  
Then I'll get back to you.

Thanks.

**Comment by Byloth** [comment]
It seems to be a known problem...  
Here the user `Mein Name ist Hase` explained it: https://discord.com/channels/362206349339262976/362206349339262978/1285873267168772146

It have to be solved on the original CMaNGOS project; I'm gonna open a PR to solve this problem.

**Comment by nosralan1** [comment]
Hi.

Thank you very much for your fast support and your great work with Docker!
I will look out for an update of cmangos project.

BR

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Byloth** [comment]
I've opened a PR where I've solved this issue, on the [original CMaNGOS repository](https://github.com/cmangos/wotlk-db/).  
Once it is accepted, this issue will be solved.

Until then, we can only wait...  
However, if you are proficient with Docker, you can apply the few lines of code from the PR directly inside your container.

---

I'll close this Issue as soon as the PR request is accepted.

**Comment by Byloth** [comment]
The problem has been solved.  
You may need to pull again the Docker images to get the latest version:

```sh
docker pull ghcr.io/byloth/cmangos/wotlk:latest
docker pull ghcr.io/byloth/cmangos/wotlk/builder:latest
```

---

Once pulled the new versions, try again with the `init-db` command.

Thanks for your patience. 🙃

**Comment by nosralan1** [comment]
I have reloaded the image and it works as expected. Thank you very much!


________________________________
